name = "vfdashboard"
pages_build_output_dir = "./dist"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VFDashboard"
id = "7b220308d67840c6bc90cd104efa145b"
